name: Audit and test install

on: [push, pull_request]

jobs:
  audit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Audit
        run: make test

      - name: Test install
        run: make test-install
